WIFI_SSID = "<WIFI-SSID>"     # use CIRCUITPY_WIFI_SSID for (always) enabled CPY web workflow
WIFI_PSK  = "<WIKI-PASSWORD>"    # use CIRCUITPY_WIFI_PSK  for (always) enabled CPY web workflow

[SYSTEM]
DEBUG = 0                       # activate to wait on startup for console connection
PRINTER_USB_VID = "04b8"        # EPSON
PRINTER_USB_PID = "0e15"        # TM-T20II
# TODO: NTP
# TODO: option to enable web workflow in boot.py if resetted by software ...

[ESCPOS]
SERVICES = [ "MQTT", "TCP" ]           # services that shall be started

[SERVICE:HTTP]
SERVER_IPV4 = "0.0.0.0"
SERVER_PORT = 8080
SERVER_PATH = "/escpos"

[SERVICE:MQTT]
BROKER_IPV4 = "192.168.4.1"
#BROKER_USER = "YOUR-MQTT-USERNAME"
#BROKER_PASS = "YOUR-MQTT-PASSWORD"
BROKER_TOPIC = "printer/my-printer/escpos"

[SERVICE:TCP]
SERVER_IPV4 = "0.0.0.0"
SERVER_PORT = 9100
CLIENT_TIMEOUT = 3

