#WIFI_SSID = "<WIFI-SSID>"     # use CIRCUITPY_WIFI_SSID for (always) enabled CPY web workflow
#WIFI_PSK  = "<WIFI-PASS>"     # use CIRCUITPY_WIFI_PSK  for (always) enabled CPY web workflow

[SYSTEM]
DEBUG = 1                      # activate to wait on startup for console connection
# TODO: NTP
# TODO: option to enable web workflow in boot.py if resetted by software ...

[ESCPOS]
SERVICES = [ "TCP" ]           # services that shall be started
PRINTERS = [ "TM-T20II", "DEBUG" ]


[SERVICE:HTTP]
SERVER_IPV4 = "0.0.0.0"
SERVER_PORT = 8080
SERVER_PATH = "/escpos"

[SERVICE:MQTT]
BROKER_IPV4 = "192.168.4.1"
#BROKER_USER = "YOUR-MQTT-USERNAME"
#BROKER_PASS = "YOUR-MQTT-PASSWORD"
BROKER_TOPIC = "printer/my-printer/escpos"

[SERVICE:TCP]
SERVER_IPV4 = "0.0.0.0"
SERVER_PORT = 9100
CLIENT_TIMEOUT = 3


[PRINTER:TM-T20II]
DRIVER = "USB"
VID = "04b8"        # EPSON
PID = "0e15"        # TM-T20II

[PRINTER:TM-T88IV]
DRIVER = "USB"
VID = "04b8"        # EPSON
PID = "0202"        # TM-T88IV

