#WIFI_SSID = "<WIFI-SSID>"     # use CIRCUITPY_WIFI_SSID      for (always) enabled CPY web workflow
#WIFI_PSK  = "<WIFI-PASS>"     # use CIRCUITPY_WIFI_PASSWORD  for (always) enabled CPY web workflow

[SYSTEM]
LOG_LEVEL = "DEBUG"
#LOG_SERVER = "192.168.1.1"
#LOG_PRINTER = "TM-T20II"
USB_HOST_PIN_DP = "GP26"       # required for USB printer(s), specific to board; GP26 is a PicoW specific pin name
USB_HOST_PIN_DM = "GP27"       # required for USB printer(s), specific to board; GP27 is a PicoW specific pin name

[ESCPOS]
SERVICES = [ "RAW" ]               # services that shall be started
PRINTERS = [ "TM-T20II", "DEBUG" ] # printers that shall receive printjobs


[SERVICE:HTTP]
DRIVER = "HTTP"
SERVER_IPV4 = "0.0.0.0"                    # default = "0.0.0.0"
SERVER_PORT = 8080                         # default = 8080
SERVER_PATH = "/escpos"                    # default = "/"

[SERVICE:MQTT]
DRIVER = "MQTT"
BROKER_IPV4 = "192.168.4.1"                # mandatory
#BROKER_USER = "YOUR-MQTT-USERNAME"        # optional, unless required by broker
#BROKER_PASS = "YOUR-MQTT-PASSWORD"        # optional, unless required by broker
BROKER_TOPIC = "printer/my-printer/escpos" # mandatory

[SERVICE:RAW]
DRIVER = "TCP"
SERVER_IPV4 = "0.0.0.0"                    # default = "0.0.0.0"
SERVER_PORT = 9100                         # default = 9100
CLIENT_TIMEOUT = 3                         # default = 3


[PRINTER:DEBUG]
DRIVER="DEBUG"

[PRINTER:TM-T20II]
DRIVER = "USB"
USB_VID = "04b8"                           # mandatory, 04b8 = EPSON
USB_PID = "0e15"                           # mandatory, 0e15 = TM-T20II
#ESCPOS-INIT = ""                          # default = "1b401b6404" => reset & feed 4 lines
#ESCPOS-FINI = ""                          # default = "1b64081b6d" => feed 8 lines & partial cut

[PRINTER:TM-T88IV]
DRIVER = "USB"
USB_VID = "04b8"                           # mandatory, 04b8 = EPSON
USB_PID = "0202"                           # mandatory, 0202 = TM-T88IV
#ESCPOS-INIT = ""                          # default = "1b401b6404" => reset & feed 4 lines
#ESCPOS-FINI = ""                          # default = "1b64081b6d" => feed 8 lines & partial cut

